# Generated by Django 6.0.6 on 2026-07-12 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('round', models.IntegerField(blank=True, null=True)),
                ('white_player', models.CharField(max_length=50)),
                ('black_player', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=10)),
                ('white_elo', models.IntegerField(blank=True, null=True)),
                ('black_elo', models.IntegerField(blank=True, null=True)),
                ('time_control', models.CharField(max_length=25)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('termination', models.CharField(max_length=50)),
                ('eco_code', models.CharField(blank=True, max_length=10)),
                ('fen_matches_array', models.JSONField(blank=True, default=list)),
                ('opening_line', models.CharField(blank=True, max_length=200)),
                ('opening_family', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('white_move', models.CharField(max_length=10)),
                ('black_move', models.CharField(blank=True, max_length=10)),
                ('evaluation', models.FloatField(null=True)),
                ('is_blunder', models.BooleanField(default=False)),
                ('is_mistake', models.BooleanField(default=False)),
                ('is_good_move', models.BooleanField(default=False)),
                ('is_brilliant_move', models.BooleanField(default=False)),
                ('is_excellent_move', models.BooleanField(default=False)),
                ('is_superb_move', models.BooleanField(default=False)),
                ('is_perfect_move', models.BooleanField(default=False)),
                ('is_terrible_move', models.BooleanField(default=False)),
                ('is_horrible_move', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game_analyzer.game')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(default='', max_length=100)),
                ('player_name', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('opening_family_count', models.IntegerField(default=0)),
                ('opening_line_count', models.IntegerField(default=0)),
                ('opening_family_stats', models.JSONField(blank=True, default=dict)),
                ('opening_line_stats', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analyzer.game')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analyzer.report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='reports', through='game_analyzer.ReportGame', to='game_analyzer.game'),
        ),
    ]
