# Generated by Django 6.0.6 on 2026-07-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('round', models.IntegerField()),
                ('white_player', models.CharField(max_length=50)),
                ('black_player', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=10)),
                ('white_elo', models.IntegerField()),
                ('black_elo', models.IntegerField()),
                ('time_control', models.CharField(max_length=25)),
                ('end_time', models.DateTimeField()),
                ('termination', models.CharField(max_length=50)),
                ('moves', models.TextField()),
            ],
            options={
                'db_table': 'game',
            },
        ),
    ]
