# Generated by Django 6.0.6 on 2026-07-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table=None,
        ),
    ]
