# Generated by Django 6.0.6 on 2026-07-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opening_category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
