# Generated by Django 6.0.6 on 2026-07-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0002_game_opening_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='first_moves',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
