# Generated by Django 6.0.6 on 2026-07-04 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0002_alter_game_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='moves',
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('white_move', models.CharField(max_length=10)),
                ('black_move', models.CharField(blank=True, max_length=10)),
                ('evaluation', models.FloatField(null=True)),
                ('is_blunder', models.BooleanField(default=False)),
                ('is_mistake', models.BooleanField(default=False)),
                ('is_good_move', models.BooleanField(default=False)),
                ('is_brilliant_move', models.BooleanField(default=False)),
                ('is_excellent_move', models.BooleanField(default=False)),
                ('is_superb_move', models.BooleanField(default=False)),
                ('is_perfect_move', models.BooleanField(default=False)),
                ('is_terrible_move', models.BooleanField(default=False)),
                ('is_horrible_move', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game_analyzer.game')),
            ],
        ),
    ]
