# Generated by Django 6.0.6 on 2026-07-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0003_game_first_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='moves',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Move',
        ),
    ]
