# Generated by Django 6.0.6 on 2026-07-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0003_remove_game_moves_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black_elo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='white_elo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
