# Generated by Django 6.0.6 on 2026-07-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0004_alter_game_black_elo_alter_game_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
