# Generated by Django 6.0.6 on 2026-07-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0004_game_moves_delete_move'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='first_moves',
        ),
        migrations.RemoveField(
            model_name='game',
            name='opening_category',
        ),
        migrations.AddField(
            model_name='report',
            name='opening_category_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='opening_category_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
