# Generated by Django 6.0.6 on 2026-07-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0005_remove_game_first_moves_remove_game_opening_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='first_moves',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='opening_category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
