# Generated by Django 6.0.6 on 2026-07-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='eco_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='opening_family',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='opening_line',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
