# Generated by Django 6.0.6 on 2026-07-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0006_game_first_moves_game_opening_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='family_to_lines',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
