# Generated by Django 6.0.7 on 2026-08-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0007_report_family_to_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='report',
            name='family_to_lines',
        ),
        migrations.RemoveField(
            model_name='report',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='report',
            name='opening_category_count',
        ),
        migrations.RemoveField(
            model_name='report',
            name='opening_category_stats',
        ),
        migrations.RemoveField(
            model_name='report',
            name='opening_family_count',
        ),
        migrations.RemoveField(
            model_name='report',
            name='opening_family_stats',
        ),
        migrations.RemoveField(
            model_name='report',
            name='opening_line_count',
        ),
        migrations.RemoveField(
            model_name='report',
            name='opening_line_stats',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total_games',
        ),
        migrations.RemoveField(
            model_name='report',
            name='win_rate',
        ),
        migrations.RemoveField(
            model_name='report',
            name='wins',
        ),
        migrations.AddField(
            model_name='report',
            name='all_games_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='player_is_black_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='player_is_white_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
