# Generated by Django 6.0.6 on 2026-07-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0007_game_eco_code_game_opening_family_game_opening_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='first_fen_match',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
