# Generated by Django 6.0.6 on 2026-07-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0008_game_first_fen_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='second_fen_match',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
