# Generated by Django 6.0.6 on 2026-07-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0009_game_second_fen_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='first_fen_match',
        ),
        migrations.RemoveField(
            model_name='game',
            name='second_fen_match',
        ),
        migrations.AddField(
            model_name='game',
            name='fen_matches_array',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
