# Generated by Django 6.0.7 on 2026-08-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0009_alter_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='analysis_complete',
            field=models.BooleanField(default=False),
        ),
    ]
