# Generated by Django 6.0.7 on 2026-09-05 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0010_game_analysis_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pgn_file_games', to='game_analyzer.report'),
        ),
    ]
