# Generated by Django 6.1.1 on 2026-09-06 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0011_game_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moves', models.JSONField(blank=True, default=list)),
                ('fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for opponent'), ('active', 'Game in progress'), ('checkmate', 'Checkmate'), ('stalemate', 'Stalemate'), ('resigned', 'Resigned'), ('draw', 'Draw')], default='waiting', max_length=20)),
                ('result', models.CharField(blank=True, max_length=10)),
                ('time_control', models.IntegerField(default=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='black_games', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
