# Generated by Django 6.1.1 on 2026-09-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0012_livegame'),
    ]

    operations = [
        migrations.AddField(
            model_name='livegame',
            name='black_time_remaining',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='livegame',
            name='last_move_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livegame',
            name='white_time_remaining',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='livegame',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for opponent'), ('active', 'Game in progress'), ('checkmate', 'Checkmate'), ('stalemate', 'Stalemate'), ('resigned', 'Resigned'), ('draw', 'Draw'), ('timeout', 'Timeout')], default='waiting', max_length=20),
        ),
    ]
