# Generated by Django 6.1.1 on 2026-09-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analyzer', '0013_livegame_black_time_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livegame',
            name='time_mode',
            field=models.CharField(choices=[('total', 'Total time'), ('per_move', 'Time per move')], default='total', max_length=10),
        ),
    ]
