"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR.parent / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True)

# Empty is fine for local dev with DEBUG=True. Add your domain here for production.
ALLOWED_HOSTS = env('ALLOWED_HOSTS', default=[])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'game_analyzer', #This is the primary app for the project
    'rest_framework', #This is the API framework for the project
    'corsheaders', #This is the CORS framework for the project

    # Authentication dj-rest-auth
    'rest_framework.authtoken',
    'django.contrib.sites',       # required by allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',      # required even if not using social login
    'dj_rest_auth',
    'dj_rest_auth.registration',
]    

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'allauth.account.middleware.AccountMiddleware', #authentication middleware

]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
	    BASE_DIR.parent / 'frontend' / 'dist',
	],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db()
}


# Password validation   
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR.parent / 'frontend' / 'dist' / 'assets',
]

CORS_ORIGIN_WHITELIST = [
    'http://localhost:5173',
	'https://pgnlens.com',
	'https://www.pgnlens.com',
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
	'https://pgnlens.com',
	'https://www.pgnlens.com',
]

# authentication settings
SITE_ID = 1 # required by ``django.contrib.sites``, which allauth depends on

# dj-rest-auth settings
REST_AUTH = {
    'USE_JWT': False,                # use Django's token auth, not JWT
    'SESSION_LOGIN': True,           # keep session auth working too
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# allauth settings
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_LOGIN_METHODS = {'username', 'email'} # currently won't accept email unless the form field format is changed.
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_ADAPTER = 'game_analyzer.adapter.CustomAccountAdapter'

# Prints to the terminal unless production settings [below] are uncommented
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Production settings
#Gmail requires an **app password** — a 16-character password generated
#in your Google account settings (Security → 2-Step Verification →
#App passwords). Your regular Gmail password won't work.

#Add the credentials to your `.env` file:

#**Other services:** SendGrid, Mailgun, Amazon SES.

EMAIL_BACKEND = 'django.resend.backend.ResendBackend'
EMAIL_HOST = 'smtp.resend.com'
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')
