# Generated by Django 6.0.6 on 2026-06-28 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white', models.CharField(max_length=100)),
                ('black', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=10)),
                ('opening_family', models.CharField(blank=True, max_length=200)),
                ('opening_variation', models.CharField(blank=True, max_length=200)),
                ('opening_line', models.TextField(blank=True)),
                ('eco_first_match', models.CharField(blank=True, max_length=5)),
                ('eco_last_match', models.CharField(blank=True, max_length=5)),
                ('moves', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('games', models.ManyToManyField(blank=True, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
